services:
  joblist:
    build:
      context: ./job_list
      dockerfile: Dockerfile
    environment:
      - PREFIX_PORT=8080
    ports:
      - "8080:8080"

  blog:
    build:
      context: ./blog
      dockerfile: Dockerfile
    ports:
      - "8000:80"